# Generated by Django 4.2.1 on 2023-05-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedservice',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
